[riester-dev]
user = USER_NAME
group = USER_GROUP
listen = 127.0.0.1:9103
listen.allowed_clients = 127.0.0.1
; Soft mode — минимум RAM на Mac
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
pm.max_requests = 100
catch_workers_output = yes
php_admin_value[short_open_tag] = 1
php_admin_value[display_errors] = 1
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
php_admin_value[max_execution_time] = 300
php_admin_value[memory_limit] = 512M
